### ISSUE TITLE
Handle Errors 

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/aragon-profile#49]

**Comment by rkzel** [comment]
There are two types of errors. One is exceptions - most likely something to do with data, external communication, etc. They are object and should be caught and displayed appropriately. They live in state in 'error' field and applications is informed to use the error field when some flag is set (someActionFailed), or "!boxes[ethereumAddress].removedItemSuccess", or possibly even combination of flags... We might want to consider standardizing that at some point, what flags we use for actions, where and why. For now the important thing is that exceptions are caught and displayed:

![err2](https://user-images.githubusercontent.com/34452131/61125920-5c839180-a4ab-11e9-9e25-d6d81c1e4714.png)

The other kind of errors is validation errors displayed in forms, resulting from user's incorrect input. They are not exceptions, and they are strings describing field and type of problem ("incorrect date" thing).

About exceptions in modals (when an item can't be saved or removed), there is a bit of redundancy, as in the screenshot below. Exception message is displayed in the modal, so the user is properly notified, but because the error is not cleared, it is caught in LoadAndError wrapper and displayed instead of the profile. Is it correct? It is not expected to have exceptions unless... something really bad happens, so it does make sense to force the user to reload:

![err1](https://user-images.githubusercontent.com/34452131/61123953-eb8dab00-a4a5-11e9-8491-bc5e8027369c.png)
